TheLegend/TheLegend/Controllers/AskController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheLegend.Models;
using WebMatrix.WebData;

namespace TheLegend.Controllers
{
    public class AskController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Ask/

        public ActionResult Index()
        {
            var asks = db.Asks.Include(a => a.UserAsk).Include(a => a.UserOrigin).Include(a => a.UserDestin);
            return View(asks.ToList());
        }

        //
        // GET: /Ask/Details/5

        public ActionResult Details(int id = 0)
        {
            Ask ask = db.Asks.Find(id);
            if (ask == null)
            {
                return HttpNotFound();
            }
            return View(ask);
        }

        //
        // GET: /Ask/Create

        public ActionResult Create()
        {
            ViewBag.UserAskId = new SelectList(db.UserProfiles, "UserId", "UserName");
           // ViewBag.UserOriginId = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.UserDestinId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Ask/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ask ask)
        {
            ask.UserOriginId = WebSecurity.GetUserId(User.Identity.Name);
            ask.UserOrigin = db.UserProfiles.Find(ask.UserOriginId);
            if (ModelState.IsValid)
            {
                db.Asks.Add(ask);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserAskId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserAskId);
           // ViewBag.UserOriginId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserOriginId);
            ViewBag.UserDestinId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserDestinId);
            return View(ask);
        }

        //
        // GET: /Ask/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Ask ask = db.Asks.Find(id);
            if (ask == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserAskId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserAskId);
            ViewBag.UserOriginId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserOriginId);
            ViewBag.UserDestinId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserDestinId);
            return View(ask);
        }

        //
        // POST: /Ask/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Ask ask)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ask).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserAskId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserAskId);
            ViewBag.UserOriginId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserOriginId);
            ViewBag.UserDestinId = new SelectList(db.UserProfiles, "UserId", "UserName", ask.UserDestinId);
            return View(ask);
        }

        //
        // GET: /Ask/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Ask ask = db.Asks.Find(id);
            if (ask == null)
            {
                return HttpNotFound();
            }
            return View(ask);
        }

        //
        // POST: /Ask/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ask ask = db.Asks.Find(id);
            db.Asks.Remove(ask);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Responder(int id = 0)
        {
            Ask ask = db.Asks.Find(id);
            Introdution introdution = new Introdution();

            //User que Originou o pedido
            UserProfile user = db.UserProfiles.Find(ask.UserOriginId);


            //Procurar na lista de missions a missom que esta activa para o User que Originou o pedido
            Mission[] auxmisson = db.Missions.ToArray();

            Mission mission = new Mission();

            for (int i = 0; i < auxmisson.Length; i++)
            {
                if (auxmisson[i].UserMissionId == ask.UserOriginId)
                {
                    if (!auxmisson[i].IsComplete)
                    {
                        mission = auxmisson[i];
                    }
                }
            }

            //Preencher a Introdution
            introdution.MissionId = mission.MissionId;
            introdution.mission = mission;
            introdution.UserOriginId = ask.UserOriginId;
            introdution.UserOrigin = db.UserProfiles.Find(ask.UserOriginId);
            introdution.UserDestinId = ask.UserDestinId;
            introdution.UserDestin = db.UserProfiles.Find(ask.UserDestinId);
            introdution.StateId = 1;
            introdution.state = db.States.Find(1);
            introdution.GameId = 4;
            introdution.game = db.Games.Find(4);
            introdution.GameResult = false;

            db.Asks.Remove(ask);
            db.SaveChanges();

            db.Introdutions.Add(introdution);
            db.SaveChanges();

            return RedirectToAction("Index", "Introdution");
        }
    }
}

TheLegend/TheLegend/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheLegend.Filters;
using TheLegend.Models;
using WebMatrix.WebData;



namespace TheLegend.Controllers
{
    public class PerfilController : Controller
    {
         private UsersContext bd = new UsersContext();

        public ActionResult Index()
        {
            return View(bd.UserProfiles.ToList());
        }

        //metodo para mostrar os dados 
        public ActionResult Edit(int id = 0)
        {
            UserProfile user = bd.UserProfiles.Find(id);
            ViewBag.HumorId = new SelectList(bd.Humors, "HumorId", "EstadoHumor");
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // metodo de ediçao

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile user)
        {
            if (ModelState.IsValid)
            {
                bd.Entry(user).State = EntityState.Modified;
                bd.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }
         [InitializeSimpleMembership]
        public ActionResult Eliminar(int id=0)
        {
           UserProfile user = bd.UserProfiles.Find(WebSecurity.GetUserId(User.Identity.Name));
            Tag t = bd.Tags.Find(id);
            user.Tags.Remove(t);
            bd.SaveChanges();
                return RedirectToAction("Index");
           
        }

    }
}

TheLegend/TheLegend/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheLegend.Models;

namespace TheLegend.Controllers
{
    public class StateController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /State/

        public ActionResult Index()
        {
            return View(db.States.ToList());
        }

        //
        // GET: /State/Details/5

        public ActionResult Details(int id = 0)
        {
            State state = db.States.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }

        //
        // GET: /State/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /State/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(State state)
        {
            if (ModelState.IsValid)
            {
                db.States.Add(state);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(state);
        }

        //
        // GET: /State/Edit/5

        public ActionResult Edit(int id = 0)
        {
            State state = db.States.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }

        //
        // POST: /State/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(State state)
        {
            if (ModelState.IsValid)
            {
                db.Entry(state).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(state);
        }

        //
        // GET: /State/Delete/5

        public ActionResult Delete(int id = 0)
        {
            State state = db.States.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }

        //
        // POST: /State/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            State state = db.States.Find(id);
            db.States.Remove(state);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TheLegend/TheLegend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Your Legendary Game</title>
        
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
            </head>
<body >
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("Game", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Tag", "Index", "Tag")</li>
                            <li>@Html.ActionLink("O Meu Perfil", "Index", "Perfil")</li>
                            <li>@Html.ActionLink("Pedidos", "Index", "Ask")</li>
                            @*<li>@Html.ActionLink("Humor", "Index", "Humor")</li>*@
                            <li>@Html.ActionLink("Missião", "Index", "Mission")</li>
                            @*<li>@Html.ActionLink("TagRelation", "Index", "TagRelation")</li>
                                <li>@Html.ActionLink("Jogos", "Index", "Game")</li>
                                <li>@Html.ActionLink("Estados", "Index", "State")</li>*@
                            <li>@Html.ActionLink("Introduções", "Index", "Introdution")</li>
                            <li>@Html.ActionLink("Amigos", "Index", "RelationShip")</li>
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - The Legend </p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>